### ISSUE TITLE
1차 배포 & 피드백 현황

### ISSUE THREAD

**Issue by 2Zero1** [CodeSoom/project-react-3-2Zero1#178]
### 1차 배포 현황
1. 사용자는 상대방으로 부터 받은 메시지에 있는 url을 통해 엽서 입장 페이지에 접근할 수 있다.
2. 사용자는 엽서를 확인할 수 있다.
3. 사용자는 사진과 메시지를 넣어 엽서를 작성할 수 있다.
4. 사용자는 작성한 엽서를 미리보기를 통해 먼저 확인할 수 있다.
5. 사용자는 작성 완료한 엽서의 링크를 복사하여 친구에게 전송할 수 있다.

### 피드백
1. 비밀 메시지가 헷갈린다.
    a. 엽서가 비공개로 작성될 경우 비밀 메시지가 무엇인지 헷갈린다. 비밀번호 같은데 이름을 비밀번호로 바꿔야할 것같다.
    b.엽서가 비공개로 작성될 경우 비밀 메시지를 입력 해야 하는데 입력해야될게 비밀메시지인지 몰랐다. 서로만의 아는 메시지로 의미를 두고싶다면 '접선 암호' 라는 식으로 해도 될것 같다.

2. 엽서 앞면에 우표로 사진이 붙어 있는데, 우표 이미지로 꾸며도 좋을 것 같다.
3. 엽서 작성시 이미지 업로드를 선택 적으로 할 수 있었으면 좋겠다. 이미지를 업로드 하지 않을 경우엔 엽서 페이지에서 기본 이미지가 보여졌으면 좋겠다.
4. 옆서페이지에 들어갔을때 뒷면이 있는지 몰랐었다.

### 결정 사항

- [x] 1. 엽서 암호로 변경 

- [x] 2. 엽서 앞면에 사진을 우표 이미지로 꾸민다.

**Comment by moonkii** [comment]
'엽서 암호' 라고 하는건 어떨까요?

**Comment by 2Zero1** [comment]
> '엽서 암호' 라고 하는건 어떨까요?

좋은것 같습니다 ~
